#IMAGEM PARA CRIAR O CONTAINER
FROM node:alpine

#lOCAL DE TRABALHO DO CONTAINER
WORKDIR /user/app

#COPIAR TUDO QUE COMEÇA COM PACKAGE E TUDO QUE TERMINA COM JSON
COPY package.json ./

#INSTALAR A NODE_MODELS DENTRO DO CONTAINER
RUN npm install

#COPIAR TUDO DA PASTA RAIZ PARA DENTRO DO CONTAINER 
COPY . .

#PORTAR DO CONTAINER QUE DESEJA EXPOR PARA SEU HOST
EXPOSE 3333

#INDICA QUAL COMANDO DEVE EXECUTAR PARA STARTA O APP
CMD ["npm", "start"]
